import { chromium } from 'playwright'
const b = await chromium.launch({ channel: 'chrome', headless: true })
const p = await b.newPage({ viewport: { width: 1920, height: 1080 } })
await p.goto('http://127.0.0.1:8000', { waitUntil: 'networkidle' })
await p.waitForSelector('.planner')
await p.waitForTimeout(3000)
await p.click('.btn-primary.wide')
await p.waitForSelector('.metrics', { timeout: 120000 })
await p.waitForTimeout(4000)
await p.waitForFunction(() => {
  const imgs = [...document.querySelectorAll('.leaflet-tile')]
  return imgs.length > 0 && imgs.every((i) => i.classList.contains('leaflet-tile-loaded') || !i.complete)
}, { timeout: 20000 }).catch(() => {})
await p.waitForTimeout(800)
const box = await (await p.$('.basemap-switch')).boundingBox()
console.log('basemap-switch box', JSON.stringify(box))
const el = await p.$('.basemap-switch')
console.log('visible in vp:', await el.isVisible())
await p.screenshot({ path: 'verify/shots/geo-00-optimized.png' })
await p.locator('.mapcol').screenshot({ path: 'verify/shots/geo-00-map.png' })
await b.close()
